# .github/FUNDING.yml

github: [tienld-0801]
patreon: foothienld
open_collective: tilokit
ko_fi: tienld
buy_me_a_coffee: tienld
liberapay: tienld
issuehunt: tienld
custom: https://github.com/sponsors/tienld-0801
