package nextjs

// App Router Templates (Next.js 13+ with app directory)
const (
	// TypeScript version for App Router
	NextjsAppPackageJsonTS = `{
  "name": "<<TILO:.project_name>>",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "<<TILO:.next_version>>",
    "react": "<<TILO:.react_version>>",
    "react-dom": "<<TILO:.react_dom_version>>"
  },
  "devDependencies": {
    "@types/node": "^20.0.0",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "autoprefixer": "^10.0.1",
    "eslint": "^8.0.0",
    "eslint-config-next": "<<TILO:.next_version>>",
    "postcss": "^8.4.0",
    "tailwindcss": "^3.3.0",
    "typescript": "^5.0.0"
  }
}`

	// JavaScript version removed - Next.js only supports TypeScript
	NextjsAppPackageJsonJS = ``

	// Root layout for App Router
	NextjsAppLayoutPage = `import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '<<TILO:.project_name>>',
  description: 'Generated by TiLoKit with Next.js App Router',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}`

	// Home page for App Router
	NextjsAppHomePage = `export default function Home() {
  return (
    <main className="container mx-auto px-4 py-8">
      <h1 className="text-4xl font-bold text-center mb-8">
        Welcome to <<TILO:.project_name>>
      </h1>
      <p className="text-lg text-gray-600">This is a Next.js application created with TiLoKit.</p>
      <p>This application uses Next.js <strong>App Router</strong> with TypeScript and Tailwind CSS.</p>
      <div className="flex justify-center">
        <a
          href="/about"
          className="bg-blue-500 hover:bg-blue-600 text-white px-6 py-3 rounded-lg transition-colors"
        >
          Learn More
        </a>
      </div>
    </main>
  )
}`

	// About page for App Router
	NextjsAppAboutPage = `export default function About() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold mb-4">About <<TILO:.project_name>></h1>
      <p className="text-lg text-gray-600">This is a Next.js application created with TiLoKit.</p>
      <p>This application uses Next.js <strong>App Router</strong> with TypeScript and Tailwind CSS.</p>
      <div className="flex justify-center">
        <a
          href="/"
          className="bg-green-500 hover:bg-green-600 text-white px-6 py-3 rounded-lg transition-colors"
        >
          Go Home
        </a>
      </div>
    </main>
  )
}`

	// Global CSS with Tailwind
	NextjsAppGlobalCSS = `@tailwind base;
@tailwind components;
@tailwind utilities;

/* Custom styles */
body {
  font-family: 'Inter', sans-serif;
}
`

	// Tailwind config for App Router
	NextjsAppTailwindConfig = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
}
`

	// PostCSS config
	NextjsAppPostCSSConfig = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`
)
