package nextjs

// App Router Templates (Next.js 13+ with app directory)
const (
	// Package.json with Tailwind CSS for App Router
	NextjsAppPackageJson = `{
  "name": "{{.ProjectName}}",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.0.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
  "devDependencies": {
    "@types/node": "^20.0.0",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "autoprefixer": "^10.0.1",
    "eslint": "^8.0.0",
    "eslint-config-next": "14.0.0",
    "postcss": "^8.4.0",
    "tailwindcss": "^3.3.0",
    "typescript": "^5.0.0"
  }
}`

	// Root layout for App Router
	NextjsAppLayout = `import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '{{.ProjectName}}',
  description: 'Generated by TiLoKit with Next.js App Router',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}`

	// Main page for App Router
	NextjsAppPage = `export default function Home() {
  return (
    <main className="container mx-auto px-4 py-8">
      <h1 className="text-4xl font-bold text-center mb-8">
        Welcome to {{.ProjectName}}
      </h1>
      <p className="text-lg text-center text-gray-600">
        Get started by editing <code className="bg-gray-100 px-2 py-1 rounded">app/page.tsx</code>
      </p>
      <div className="flex justify-center mt-8">
        <a 
          href="/about" 
          className="bg-blue-500 hover:bg-blue-600 text-white px-6 py-3 rounded-lg transition-colors"
        >
          Learn More
        </a>
      </div>
    </main>
  )
}`

	// About page for App Router
	NextjsAppAboutPage = `export default function About() {
  return (
    <main className="container mx-auto px-4 py-8">
      <h1 className="text-4xl font-bold text-center mb-8">
        About {{.ProjectName}}
      </h1>
      <p className="text-lg text-center text-gray-600 mb-8">
        This is a Next.js application using <strong>App Router</strong> with TypeScript and Tailwind CSS.
      </p>
      <div className="flex justify-center">
        <a 
          href="/" 
          className="bg-green-500 hover:bg-green-600 text-white px-6 py-3 rounded-lg transition-colors"
        >
          Go Home
        </a>
      </div>
    </main>
  )
}`

	// Global CSS with Tailwind
	NextjsAppGlobalCSS = `@tailwind base;
@tailwind components;
@tailwind utilities;

/* Custom styles */
body {
  font-family: 'Inter', sans-serif;
}
`

	// Tailwind config for App Router
	NextjsAppTailwindConfig = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
}
`

	// PostCSS config
	NextjsAppPostCSSConfig = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`
)
